apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mkcert-ca-issuer
spec:
  ca:
    secretName: mkcert-ca

---

apiVersion: v1
kind: Secret
metadata:
  name: movie-database-tls
  annotations:
    kubed.appscode.com/sync: ""
data:
  ca.crt: ''
  tls.crt: ''
  tls.key: ''
type: kubernetes.io/tls

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: movie-database
spec:
  issuerRef:
    kind: ClusterIssuer
    name: mkcert-ca-issuer
  dnsNames:
    - movie-database.pl
  secretName: movie-database-tls
