apiVersion: v1
kind: Service
metadata:
  name: movie-database-frontend
spec:
  selector:
    app: movie-database-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-database-frontend
spec:
  selector:
    matchLabels:
      app: movie-database-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: movie-database-frontend
    spec:
      containers:
        - name: movie-database-frontend
          image: movie-database-frontend:latest
          imagePullPolicy: Never
